[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
startupTimeout = 180
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["nodejs", "npm"]
